name: Build Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name
      
      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-image-name ${{ secrets.DOCKER_USERNAME }}/my-image-name
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name
